
/****** Object:  Table [dbo].[MOVIMENTO_MANUAL]    Script Date: 30/11/2021 15:46:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MOVIMENTO_MANUAL](
	[DAT_MES] [numeric](2,0) NOT NULL,
	[DAT_ANO] [numeric](4,0) NOT NULL,
	[NUM_LANCAMENTO] [numeric](18,0) NOT NULL,
	[COD_PRODUTO] [char](4) NOT NULL,
	[COD_COSIF] [char](11) NOT NULL,
	[DES_DESCRICAO] [varchar](50) NOT NULL,
	[DAT_MOVIMENTO] [smalldatetime] NOT NULL,
	[COD_USUARIO] [varchar](15) NOT NULL,
	[VAL_VALOR] [numeric](18,2) NOT NULL,
 CONSTRAINT [PK_MOVIMENTO_MANUAL] PRIMARY KEY CLUSTERED 
(
	[DAT_MES] ASC,
	[DAT_ANO] ASC,
	[NUM_LANCAMENTO] ASC,
	[COD_PRODUTO] ASC,
	[COD_COSIF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- ***** ÍNDICES *****


CREATE NONCLUSTERED INDEX [IX_ANO_MES] ON [dbo].[MOVIMENTO_MANUAL]
(
	[DAT_ANO] ASC,
	[DAT_MES] ASC,
	[NUM_LANCAMENTO] ASC,
	[COD_PRODUTO] ASC,
	[COD_COSIF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_NUM_LANCAMENTO] ON [dbo].[MOVIMENTO_MANUAL]
(
	[NUM_LANCAMENTO] ASC,
	[DAT_MES] ASC,
	[DAT_ANO] ASC,
	[COD_PRODUTO] ASC,
	[COD_COSIF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_COD_PRODUTO] ON [dbo].[MOVIMENTO_MANUAL]
(
	[COD_PRODUTO] ASC,
	[COD_COSIF] ASC,
	[DAT_MES] ASC,
	[DAT_ANO] ASC,
	[NUM_LANCAMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_COD_COSIF] ON [dbo].[MOVIMENTO_MANUAL]
(
	[COD_COSIF] ASC,
	[COD_PRODUTO] ASC,
	[DAT_MES] ASC,
	[DAT_ANO] ASC,
	[NUM_LANCAMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


-- ***** RELACIONAMENTOS *****

ALTER TABLE [dbo].[MOVIMENTO_MANUAL]  WITH CHECK ADD  CONSTRAINT [FK_MOVIMENTO_MANUAL_PRODUTO_COSIF] FOREIGN KEY([COD_PRODUTO], [COD_COSIF])
REFERENCES [dbo].[PRODUTO_COSIF] ([COD_PRODUTO], [COD_COSIF])
GO

ALTER TABLE [dbo].[MOVIMENTO_MANUAL] CHECK CONSTRAINT [FK_MOVIMENTO_MANUAL_PRODUTO_COSIF]
GO


