
/****** Object:  Table [dbo].[PRODUTO_COSIF]    Script Date: 30/11/2021 15:46:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUTO_COSIF](
	[COD_PRODUTO] [char](4) NOT NULL,
	[COD_COSIF] [char](11) NOT NULL,
	[COD_CLASSIFICACAO] [char](6) NULL,
	[STA_STATUS] [char](1) NULL,
 CONSTRAINT [PK_PRODUTO_COSIF] PRIMARY KEY CLUSTERED 
(
	[COD_PRODUTO] ASC,
	[COD_COSIF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- ***** ÍNDICES *****


CREATE NONCLUSTERED INDEX [IX_COD_PRODUTO] ON [dbo].[PRODUTO_COSIF]
(
	[COD_PRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_COD_COSIF] ON [dbo].[PRODUTO_COSIF]
(
	[COD_COSIF] ASC,
	[COD_PRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_COD_CLASSIFICACAO] ON [dbo].[PRODUTO_COSIF]
(
	[COD_CLASSIFICACAO] ASC,
	[COD_PRODUTO] ASC,
	[COD_COSIF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_STA_STATUS] ON [dbo].[PRODUTO_COSIF]
(
	[STA_STATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


-- ***** RELACIONAMENTOS *****

ALTER TABLE [dbo].[PRODUTO_COSIF]  WITH CHECK ADD  CONSTRAINT [FK_PRODUTO_COSIF_PRODUTO] FOREIGN KEY([COD_PRODUTO])
REFERENCES [dbo].[PRODUTO] ([COD_PRODUTO])
GO

ALTER TABLE [dbo].[PRODUTO_COSIF] CHECK CONSTRAINT [FK_PRODUTO_COSIF_PRODUTO]
GO


-- ***** POPULAR DADOS *****

INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) (SELECT '0001', 'EMPRESA 1', '000000', '1')
INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) (SELECT '0002', 'EMPRESA 1', '111111', '1')
INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) (SELECT '0003', 'EMPRESA 1', '222222', '1')
INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) (SELECT '0004', 'EMPRESA 1', '333333', '1')
INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) (SELECT '0005', 'EMPRESA 1', '444444', '1')
INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) (SELECT '0006', 'EMPRESA 1', '555555', '1')
INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) (SELECT '0007', 'EMPRESA 1', '666666', '1')
INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) (SELECT '0008', 'EMPRESA 1', '777777', '1')
INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) (SELECT '0009', 'EMPRESA 1', '888888', '1')
INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) (SELECT '0010', 'EMPRESA 1', '999999', '1')

