
/****** Object:  Table [dbo].[PRODUTO]    Script Date: 30/11/2021 15:46:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUTO](
	[COD_PRODUTO] [char](4) NOT NULL,
	[DES_PRODUTO] [varchar](30) NULL,
	[STA_STATUS] [char](1) NULL,
 CONSTRAINT [PK_PRODUTO] PRIMARY KEY CLUSTERED 
(
	[COD_PRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- ***** ÍNDICES *****


CREATE NONCLUSTERED INDEX [IX_DES_PRODUTO] ON [dbo].[PRODUTO]
(
	[DES_PRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_STA_STATUS] ON [dbo].[PRODUTO]
(
	[STA_STATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


-- ***** RELACIONAMENTOS *****



-- ***** POPULAR DADOS *****

INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) (SELECT '0001', 'PRODUTO 1', '1')
INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) (SELECT '0002', 'PRODUTO 2', '1')
INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) (SELECT '0003', 'PRODUTO 3', '1')
INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) (SELECT '0004', 'PRODUTO 4', '1')
INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) (SELECT '0005', 'PRODUTO 5', '1')
INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) (SELECT '0006', 'PRODUTO 6', '1')
INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) (SELECT '0007', 'PRODUTO 7', '1')
INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) (SELECT '0008', 'PRODUTO 8', '1')
INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) (SELECT '0009', 'PRODUTO 9', '1')
INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) (SELECT '0010', 'PRODUTO 10', '1')

