//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSM.Database.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbPSMEntities : DbContext
    {
        public dbPSMEntities()
            : base("name=dbPSMEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MOVIMENTO_MANUAL> MOVIMENTO_MANUAL { get; set; }
        public virtual DbSet<PRODUTO> PRODUTO { get; set; }
        public virtual DbSet<PRODUTO_COSIF> PRODUTO_COSIF { get; set; }
        public virtual DbSet<VW_MOVIMENTO_MANUAL> VW_MOVIMENTO_MANUAL { get; set; }
    }
}
